apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

replicas:
- count: 1
  name: frontend

images:
- name: frontend-image
  newName: 833558168913.dkr.ecr.ap-northeast-2.amazonaws.com/user13-frontend-repo
  newTag: latest

patches:
- path: resource-patch.yaml
  target:
    kind: Deployment
    name: frontend
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: frontend-config
